apiVersion: v1
kind: Namespace
metadata:
  name: its1-system
  labels:
    app.kubernetes.io/part-of: kubestellar
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: its1
  labels:
    app.kubernetes.io/name: controlplane
    app.kubernetes.io/instance: its1
    app.kubernetes.io/part-of: kubestellar
    kflex.kubestellar.org/role: its
spec:
  type: host
---
apiVersion: v1
kind: Namespace
metadata:
  name: wds1-system
  labels:
    app.kubernetes.io/part-of: kubestellar
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: wds1
  labels:
    app.kubernetes.io/name: controlplane
    app.kubernetes.io/instance: wds1
    app.kubernetes.io/part-of: kubestellar
    kflex.kubestellar.org/role: wds
spec:
  type: k8s
  backend: shared
